global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ip2country-service'
    static_configs:
      - targets: ['ip2country-service:8080']

  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: ['mongodb-exporter:9216']
  
  - job_name: 'redis-exporter'
  static_configs:
    - targets: ['redis-exporter:9121']

